const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const dirsToScan = [
  rootDir,
  path.join(rootDir, 'ADR'),
  path.join(rootDir, 'Guides')
];

let extractedChecks = [];

const regex = /```javascript feature-check\s*\n([\s\S]*?)```/g;

dirsToScan.forEach(dir => {
  if (!fs.existsSync(dir)) return;
  const files = fs.readdirSync(dir);
  files.forEach(file => {
    if (file.endsWith('.md')) {
      const filePath = path.join(dir, file);
      const content = fs.readFileSync(filePath, 'utf8');
      
      let match;
      while ((match = regex.exec(content)) !== null) {
        let code = match[1].trim();
        if (!code.endsWith(',')) code += ',';
        extractedChecks.push(code);
      }
    }
  });
});

const outPath = path.join(rootDir, 'website', 'js', 'healthcheck.js');

const jsContent = `/* 
 * AUTO-GENERATED FILE BY tools/build_healthcheck.js 
 * Do not edit this file directly! 
 * Edit the \`\`\`javascript feature-check blocks in the Markdown documents instead.
 */

export function runLiveDiagnostics() {
  const f = (name, supported, baseline, rec) => ({ name, supported, baseline, rec });

  const features = [
    ${extractedChecks.join('\n    ').replace(/,\s*$/, '')}
  ];

  const tbody = document.getElementById("diag-results");
  const timestamp = document.getElementById("diag-timestamp");
  
  if (timestamp) {
    timestamp.textContent = typeof Temporal !== 'undefined' ? Temporal.Now.plainTimeISO().toString().split('.')[0] : 'Time';
  }

  if (tbody) {
    const htmlStr = features.map(feat => {
      const statusIcon = feat.supported ? "🟢 READY" : "🔴 PENDING";
      const statusClass = feat.supported ? "ready" : "pending";
      return \`
        <tr>
          <td><strong>\${feat.name}</strong></td>
          <td class="status-cell \${statusClass}">\${statusIcon}</td>
          <td><code>\${feat.baseline}</code></td>
          <td><em>\${feat.rec}</em></td>
        </tr>
      \`;
    }).join("");
    if (tbody.setHTML) {
       tbody.setHTML(htmlStr);
    } else if (tbody.setHTMLUnsafe) {
       tbody.setHTMLUnsafe(htmlStr);
    } else {
       tbody.innerHTML = htmlStr;
    }
  }
  
  return features;
}
`;

fs.writeFileSync(outPath, jsContent, 'utf8');
console.log('Successfully compiled website/js/healthcheck.js with ' + extractedChecks.length + ' checks.');

