// @adr [[ADR-JS]] 
// @guide [[testing-guide]] 

/* 
 * AUTO-GENERATED FILE BY tools/build_healthcheck.js 
 * Do not edit this file directly! 
 * Edit the ```javascript feature-check blocks in the Markdown documents instead.
 */

export function runLiveDiagnostics() {
  const f = (name, supported, baseline, rec) => ({ name, supported, baseline, rec });

  const features = [
    // f("Feature Name", Bedingung, "Chrome XXX", "Status")
f("CSS :has() Selektor", typeof CSS !== "undefined" && CSS.supports && CSS.supports("selector(:has(div))"), "Chrome 105", "Produktiv"),
f("CSS field-sizing: content", typeof CSS !== "undefined" && CSS.supports && CSS.supports("field-sizing: content"), "Chrome 123", "Produktiv"),
    f("Geoapify Autocomplete", typeof globalThis.fetch === "function", "Chrome 42", "Produktiv"),
f("CSS Anchor Positioning", CSS.supports("anchor-name: --test"), "Chrome 125", "Produktiv"),
    f("Temporal API", typeof globalThis.Temporal !== "undefined", "Chrome 146", "Future-Proof"),
f("View Transitions (Scoped)", typeof document.startViewTransition !== "undefined", "Chrome 146", "Future-Proof"),
f("Sanitizer API (Native)", typeof globalThis.Sanitizer !== "undefined", "Chrome 147", "Future-Proof"),
f("Promise.withResolvers()", typeof Promise.withResolvers !== "undefined", "Chrome 119", "Produktiv"),
    // f("Feature Name", Bedingung, "Chrome XXX", "Status"),
    // f("Geoapify Native Fetch", typeof globalThis.fetch === "function", "Chrome 42", "Produktiv"),
    // f("Feature Name", typeof globalThis.Feature !== "undefined", "Chrome XXX", "Produktiv")
  ];

  const tbody = document.getElementById("diag-results");
  const timestamp = document.getElementById("diag-timestamp");
  
  if (timestamp) {
    timestamp.textContent = typeof Temporal !== 'undefined' ? Temporal.Now.plainTimeISO().toString().split('.')[0] : 'Time';
  }

  if (tbody) {
    const htmlStr = features.map(feat => {
      const statusIcon = feat.supported ? "🟢 READY" : "🔴 PENDING";
      const statusClass = feat.supported ? "ready" : "pending";
      return `
        <tr>
          <td><strong>${feat.name}</strong></td>
          <td class="status-cell ${statusClass}">${statusIcon}</td>
          <td><code>${feat.baseline}</code></td>
          <td><em>${feat.rec}</em></td>
        </tr>
      `;
    }).join("");
    if (tbody.setHTML) {
       tbody.setHTML(htmlStr);
    } else if (tbody.setHTMLUnsafe) {
       tbody.setHTMLUnsafe(htmlStr);
    } else {
       tbody.innerHTML = htmlStr;
    }
  }
  
  return features;
}
